### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by jiggneshhgohel** [mint-lang/mint-website-rails#95] opened 2021-06-05 08:09 UTC
Hello,

I found a navigation issue on your mobile website. The issue is I am unable to scroll and jump to a desired topic and have to instead use the Next button at the end of each page to reach that desired topic. (FYI experiencing this on iPhone software v 14.4.2 Safari)

![25D72F67-D134-42D5-A2DD-B4A2652014FC](https://user-images.githubusercontent.com/10440841/120884848-3f0dc280-c603-11eb-93fe-a0beecdc56e4.png)

Thanks.

**Comment by Sija** [comment] 2021-06-24 12:10
Duplicate of #84

**Closed by Sija** 2021-06-24 12:10 UTC
